version: '3.8'
services:
  prometheus-container:
    container_name: prometheus-container
    depends_on:
      - driver-container
    image: prom/prometheus:latest
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - proxynet
  
  driver-container:
    container_name: driver-container
    image: metric-driver-image:latest
    volumes:
      - ../src:/opt/src
    ports:
      - "8081:8081"
    networks:
      - proxynet
  
  grafana-container:
    container_name: grafana-container
    image: grafana/grafana:latest
    volumes:
      - ../grafana:/opt/grafana
    ports:
      - "3000:3000"
    networks:
      - proxynet
    
networks:
  proxynet:
    name: metric_network
